BadWords = [
    "nigger",
    "nigga",
    "niggers",
    "niggas",
    "niggs",
    "niger",
    "nigg",
    "nig",
    "cp",
    "child",
    "r.ape",
    "ape",
    "NIIIIIII",
    "jew",
    "jewblox",
    "im hard",
    "hard dick",
    "hardcore sex",
    "jewblox",
    "im a pedophile",
    "pedo",
    "brenton tarran",
    "-51",
    "shoot some niggers up",
    "pls r.ape me",
    "r.ape me",
    "gay",
    "g@y",
    "im a faggot",
    "lgbtq",
    "ku klux klan",
    "ku klux klan best",
    "niggz ",
    ".com",
    "shit",
    "free robux",
    "robux",
    ".com",
    "bitch",
    "btch",
    "jews",
    "hangthe",
    "porn",
    "dick",
    "penis",
    "nig/ger",
    "nig/ga",
    "dox",
    "swat",
    "nig/ga",
    "rape",
    "retard",
    "fag",
    "fucked",
    "fucking",
    "ass",
    "ass hole",
    "bastard",
    "child-fucker",
    "child fucker",
    "cunt",
    "dick head",
    "nigra",
    "pigfucker",
    "piss",
    "prick",
    "pussy",
    "sisterfuck",
    "tranny",
    "twat",
    "wanker",
    "retarded",
    "retards",
    "isis",
    "allahu",
    "akbar",
    "beastiality",
    "buttfuck",
    "circlejerk",
    "cum",
    "cummer",
    "cumming",
    "cumshot",
    "dicks",
    "dildo",
    "ejaculating",
    "ejaculation",
    "ejaculat",
    "gangbang",
    "gay",
    "horny",
    "pussy",
    "vagina",
    "jackoff",
    "kkk",
    "jizz",
    "kum",
    "molest",
    "molester",
    "pedo",
    "pedophile",
    "pissing",
    "piss",
    "pornography",
    "sperm",
    "cock",
    "69420",
    "6969",
    "69 69",
    "420",
    "hentai",
    "yaoi",
    "boobs",
    "boob",
    "nipples",
    "nipple",
    "negro",
    "n1gg3r",
    ".ct8",
    "ct8",
    ".pl",
    "hitler",
    "borderhopper",
    "border hopper",
    "nigar",
    "2g1c",
    "2 girls 1 cup",
    "acrotomophilia",
    "alabama hot pocket",
    "alaskan pipeline",
    "anus",
    "apeshit",
    "arsehole",
    "ass",
    "assmunch",
    "auto erotic",
    "autoerotic",
    "babeland",
    "baby batter",
    "baby juice",
    "ball gag",
    "ball gravy",
    "ball kicking",
    "ball licking",
    "ball sack",
    "ball sucking",
    "bangbros",
    "bareback",
    "barely legal",
    "barenaked",
    "bastardo",
    "bastinado",
    "bbw",
    "bdsm",
    "beaner",
    "beaners",
    "beaver cleaver",
    "beaver lips",
    "bestiality",
    "big black",
    "big breasts",
    "big knockers",
    "big tits",
    "bimbos",
    "birdlock",
    "black cock",
    "blonde action",
    "blonde on blonde action",
    "blowjob",
    "blow job",
    "blow your load",
    "blue waffle",
    "blumpkin",
    "bondage",
    "boner",
    "booty call",
    "brown showers",
    "brunette action",
    "bukkake",
    "bulldyke",
    "bullet vibe",
    "bullshit",
    "bung hole",
    "bunghole",
    "busty",
    "butt",
    "buttcheeks",
    "butthole",
    "camel toe",
    "camgirl",
    "camslut",
    "camwhore",
    "carpet muncher",
    "carpetmuncher",
    "chocolate rosebuds",
    "cleveland steamer",
    "clitoris",
    "clover clamps",
    "clusterfuck",
    "cocks",
    "coprolagnia",
    "coprophilia",
    "cornhole",
    "coon",
    "coons",
    "creampie",
    "cunnilingus",
    "cunt",
    "darkie",
    "date rape",
    "daterape",
    "deep throat",
    "deepthroat",
    "dendrophilia",
    "dingleberry",
    "dingleberries",
    "dirty pillows",
    "dirty sanchez",
    "doggie style",
    "doggiestyle",
    "doggy style",
    "doggystyle",
    "dog style",
    "dolcett",
    "domination",
    "dominatrix",
    "dommes",
    "donkey punch",
    "double dong",
    "double penetration",
    "dp action",
    "dry hump",
    "dvda",
    "eat my ass",
    "ecchi",
    "erotic",
    "erotism",
    "escort",
    "eunuch",
    "fecal",
    "felch",
    "fellatio",
    "feltch",
    "female squirting",
    "femdom",
    "figging",
    "fingerbang",
    "fingering",
    "fisting",
    "foot fetish",
    "footjob",
    "frotting",
    "futanari",
    "gang bang",
    "gay sex",
    "genitals",
    "giant cock",
    "girl on",
    "girl on top",
    "girls gone wild",
    "goatcx",
    "goatse",
    "gokkun",
    "golden shower",
    "goodpoop",
    "goo girl",
    "goregasm",
    "grope",
    "group sex",
    "g-spot",
    "guro",
    "hardcore",
    "homoerotic",
    "honkey",
    "hooker",
    "hot carl",
    "hot chick",
    "huge fat",
    "humping",
    "incest",
    "intercourse",
    "jail bait",
    "jailbait",
    "jelly donut",
    "jigaboo",
    "jiggaboo",
    "jiggerboo",
    "juggs",
    "kike",
    "kinbaku",
    "kinkster",
    "kinky",
    "knobbing",
    "leather restraint",
    "leather straight jacket",
    "lemon party",
    "lolita",
    "lovemaking",
    "make me come",
    "male squirting",
    "masturbate",
    "menage a trois",
    "milf",
    "missionary position",
    "motherfucker",
    "mound of venus",
    "mr hands",
    "muff diver",
    "muffdiving",
    "nambla",
    "nawashi",
    "nimphomania",
    "nsfw images",
    "nudity",
    "nympho",
    "nymphomania",
    "octopussy",
    "omorashi",
    "one cup two girls",
    "one guy one jar",
    "orgasm",
    "orgy",
    "paedophile",
    "paki",
    "panties",
    "panty",
    "pedobear",
    "phone sex",
    "piece of shit",
    "piss pig",
    "pisspig",
    "playboy",
    "pleasure chest",
    "pole smoker",
    "ponyplay",
    "poof",
    "poon",
    "poontang",
    "punany",
    "poop chute",
    "poopchute",
    "prince albert piercing",
    "pthc",
    "pubes",
    "queaf",
    "queef",
    "quim",
    "raghead",
    "raging boner",
    "raping",
    "rapist",
    "rectum",
    "reverse cowgirl",
    "rimjob",
    "rimming",
    "rosy palm",
    "rosy palm and her 5 sisters",
    "rusty trombone",
    "sadism",
    "santorum",
    "scat",
    "schlong",
    "scissoring",
    "semen",
    "sexo",
    "shaved beaver",
    "shaved pussy",
    "shemale",
    "shibari",
    "shota",
    "shrimping",
    "skeet",
    "slanteye",
    "snatch",
    "snowballing",
    "sodomize",
    "sodomy",
    "spic",
    "splooge",
    "splooge moose",
    "spooge",
    "spread legs",
    "spunk",
    "strap on",
    "strapon",
    "strappado",
    "strip club",
    "style doggy",
    "sucks",
    "suicide girls",
    "sultry women",
    "swastika",
    "swinger",
    "tainted love",
    "taste my",
    "tea bagging",
    "threesome",
    "throating",
    "tied up",
    "tight white",
    "tit",
    "tits",
    "titties",
    "titty",
    "tongue in a",
    "topless",
    "tosser",
    "towelhead",
    "tranny",
    "tribadism",
    "tub girl",
    "tubgirl",
    "tushy",
    "twat",
    "twink",
    "twinkie",
    "two girls one cup",
    "undressing",
    "upskirt",
    "urethra play",
    "urophilia",
    "venus mound",
    "vibrator",
    "violet wand",
    "vorarephilia",
    "voyeur",
    "vulva",
    "wetback",
    "wet dream",
    "white power",
    "wrapping men",
    "wrinkled starfish",
    "xx",
    "xxx",
    "yellow showers",
    "yiffy",
    "zoophilia",
    "🖕",
    "dumbass",
    "bang me",
    "child porn",
    "mother fucker",
    "rape porn"
]


